### PR TITLE
Fix broken jar

### LINKED ISSUE #94: Broken Jar
The `jar-with-dependencies` does not work anymore. 

Bug reproduction steps:
```
git clone git@github.com:SpoonLabs/sonarqube-repair.git
cd sonarqube-repair
./init.sh
mvn package -DskipTests
java -jar target/sonarqube-repair-1.1-SNAPSHOT-jar-with-dependencies.jar --originalFilesPath src/test/resources/ --rulesKey 2116
```

Error output:
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at sonarquberepair.DefaultRepair.repair(DefaultRepair.java:33)
	at sonarquberepair.Main.start(Main.java:84)
	at sonarquberepair.Main.main(Main.java:90)
Caused by: java.lang.UnsupportedOperationException: No class provided, and an appropriate one cannot be found.
	at org.apache.logging.log4j.LogManager.callerClass(LogManager.java:576)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:601)
	at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:588)
	at spoon.Launcher.<clinit>(Launcher.java:589)
	... 3 more
```

On first sight it could very possibly be a dependency collision between `LogManager` of `sonarjava` and `spoon-core`  by checking line `at spoon.Launcher.<clinit>(Launcher.java:589)` . Since `spoon-core` use log4j , its [LogManager](https://logging.apache.org/log4j/2.x/log4j-api/apidocs/org/apache/logging/log4j/LogManager.html) can use the method `LogManager.getLogger()` without any arguments, while `sonarjava` use slf4j , its [LogManager](http://www.slf4j.org/api/org/apache/log4j/LogManager.html) need at least 1 argument causing the error above.

WDYT ? @fermadeiral , @monperrus  :)

### PR DESCRIPTION
**Pull request by fermadeiral**
This PR intends to fix #94.

### CODE REVIEW

**Comment by fermadeiral** [comment]
@henry-lp, now it's your turn to double-check. For now, forget about the integration with Repairnator. Let's first have a working jar, and then we see other issues later.

To sum up here, I found that the broken jar problem started when I upgraded Spoon, which was before starting using sonar-java to help in the detection of violations. So let's just use an older version of Spoon for the moment.

WDYT?

**Comment by henry-lp** [comment]
@fermadeiral can you also try downgrade spoon in #99 and check if it also works ? :)

**Comment by fermadeiral** [comment]
@henry-lp, *please*, read again what I said in the other PR and in this one.

**Comment by henry-lp** [comment]
ok, then in that case, I have no problem merging this . WDYT ? :)

**Comment by monperrus** [comment]
Thanks a lot for the fix and the constructive discussion on this tough problem.

**Comment by fermadeiral** [comment]
@monperrus, thank you for merging.

**Pull request merged**
