### PR TITLE
Allow multiple rule keys as input

### PR DESCRIPTION
**Pull request by fermadeiral**
This PR implements the feature required in #91.

See an example of transformation by 3 different processors, all applied to the same file in a single call to sonarqube-repair:

```diff
- BigDecimal bd2 = new BigDecimal(1.1); // Noncompliant by BigDecimalDoubleConstructorCheck
+ BigDecimal bd2 = BigDecimal.valueOf(1.1); 
 
- float twoThirds = 2/3; // Noncompliant by CastArithmeticOperandCheck
+ float twoThirds = (float) 2/3; 
 
  AtomicInteger aInt1 = new AtomicInteger(0);
  AtomicInteger aInt2 = new AtomicInteger(0);
- isEqual = aInt1.equals(aInt2); // Noncompliant by EqualsOnAtomicClassCheck
+ isEqual = aInt1.get() == aInt2.get(); 
```

The general idea is to receive multiple rule keys as args and, for each rule key, to create a `Launcher` with the processor corresponding to the rule key and run it. The support of multiple rules is like that because 1) all files processed by a processor (including changed and non-changed) need to be given as input to the next processor, and 2) we have the option of outputting all files or only the changed ones (see `FileOutputStrategy`). Because of all of that combined, we need an intermediate dir when multiple processors will run, which will contain all the files (changed or not changed) after all processors, except after the last one, because then we generate files in the final output path according to the `FileOutputStrategy` chosen. I added some comments in the source code that might help to understand why some things are happening.

### CODE REVIEW

**Comment by fermadeiral** [comment]
This PR is ready for review.

**Comment by fermadeiral** [comment]
> What about documenting how to use this feature in the README?

You are totally right. However, our README has not been updated at all regarding the usage of the tool. Since I don't want to create changes in this current PR that are not related to its purpose, I created a new PR for updating the README (see https://github.com/SpoonLabs/sonarqube-repair/pull/102). Once the new PR is merged, I will rebase this current PR and I will update the README with this new feature.

**Comment by monperrus** [comment]
> Once the new PR is merged, I will rebase this current PR and I will update the README with this
new feature.

ack! thanks.

**Comment by fermadeiral** [comment]
@monperrus, the update in the `README.md` is done.

**Comment by monperrus** [comment]
Thanks Fernanda!

**Pull request merged**
