### PR TITLE
Improve DefaultRepair

### PR DESCRIPTION
**Pull request by fermadeiral**
This PR improves `DefaultRepair.java`. The commit messages below are helpful to understand the performed changes.

### CODE REVIEW

**Comment by fermadeiral** [comment]
@henry-lp, this PR is my proposal per our discussion on improving `DefaultRepair`.

**Comment by henry-lp** [comment]
reviewing :)

**Comment by henry-lp** [comment]
LGTM.

**Comment by henry-lp** [comment]
Thanks , Fernanda :) .

**Pull request merged**
