### PR TITLE
[Fix] Dependency bugfixes

### PR DESCRIPTION
**Pull request by henry-lp**
This PR address #94 .

With this we don't need to compile and import local dependency from [https://github.com/fermadeiral/sonar-java](https://github.com/fermadeiral/sonar-java) anymore. 

@fermadeiral counting on you doublechecking this  :) . It passes all the tests but there might be hidden problems .
I doublechecked with Repairnator and it worked fine .

### CODE REVIEW

**Comment by fermadeiral** [comment]
@henry-lp, the problem still exists. Also, the build is passing in Travis because we don't call the jar from there, but if we do, we have a problem: see https://travis-ci.com/github/fermadeiral/sonarqube-repair/builds/163708088

So I don't know how it's possible that you have a working jar. Could you tell me exactly how you generated it, and could you also send the jar file to me by email, please?

**Comment by henry-lp** [comment]
I think it's because our Travis is using openjdk10 . Can you switch it to 8 and see if it still mess Up ?

**Comment by fermadeiral** [comment]
@henry-lp, I found that the issue is very different from what we thought. The issue has nothing to do with the changes in sonar-java, which makes this current PR not the ideal to fix the issue. I will propose a PR later when I'm available.

**Comment by henry-lp** [comment]
@fermadeiral you mean to close down this PR ? 
This has the advantage that it fixes the local dependency import which previously fail my repairnator integration.

**Comment by fermadeiral** [comment]
Henry, the bug fix and the local dependency are two very different things and we should discuss and handle them separately.

**Comment by fermadeiral** [comment]
@henry-lp, let's be more organized. This PR doesn't address what you mentioned at first, and it's messy. Please, do the following:

- Close this PR
- Try to integrate sonarqube-repair in Repairnator by using our deployed jar (I have just deployed it): https://oss.sonatype.org/content/repositories/snapshots/se/kth/castor/sonarqube-repair/1.1-SNAPSHOT/
- If the integration with Repairnator doesn't work, open an issue here, in the sonarqube-repair repository, explaining what is the issue, and then we will discuss alternatives for fixing the issue

Please, just follow the steps. We are working for the same thing, we just need to be organized and aligned.

**Comment by henry-lp** [comment]
I tried and here is the output:
```
mons.ProgressReport - 0/0 source files have been analyzed 
java.lang.NullPointerException
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.scanFiles(MultipleFilesJavaCheckVerifier.java:116)
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.verify(MultipleFilesJavaCheckVerifier.java:91)
	at org.sonar.java.checks.verifier.MultipleFilesJavaCheckVerifier.verify(MultipleFilesJavaCheckVerifier.java:58)
	at sonarquberepair.processor.SQRAbstractProcessor.<init>(SQRAbstractProcessor.java:39)
	at sonarquberepair.processor.ArrayHashCodeAndToStringProcessor.<init>(ArrayHashCodeAndToStringProcessor.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sonarquberepair.DefaultRepair.repair(DefaultRepair.java:51)
	at sonarquberepair.Main.start(Main.java:84)
	at sonarquberepair.Main.main(Main.java:90)
	at fr.inria.spirals.repairnator.process.step.repair.SonarQubeRepair.businessExecute(SonarQubeRepair.java:48)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:336)
	at fr.inria.spirals.repairnator.process.step.repair.AbstractRepairStep.execute(AbstractRepairStep.java:60)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:188)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:353)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.executeNextStep(AbstractStep.java:188)
	at fr.inria.spirals.repairnator.process.step.AbstractStep.execute(AbstractStep.java:353)
	at fr.inria.spirals.repairnator.process.inspectors.components.RunInspector4DefaultGit.run(RunInspector4DefaultGit.java:109)
	at fr.inria.spirals.repairnator.process.inspectors.ProjectInspector.run(ProjectInspector.java:301)
	at fr.inria.spirals.repairnator.pipeline.GithubMainProcess.run(GithubMainProcess.java:126)
	at fr.inria.spirals.repairnator.pipeline.BranchLauncher.main(BranchLauncher.java:97)
	at fr.inria.spirals.repairnator.pipeline.BranchLauncher.launch(BranchLauncher.java:103)
	at fr.inria.spirals.repairnator.pipeline.Launcher.main(Launcher.java:67)
done
```

Will raise an issue later.

**Comment by henry-lp** [comment]
Closing this down per request from before.

**Pull request closed without merging**
